### ISSUE TITLE
[Add  a car] The "Save" button enabled if all fields are empty.

### ISSUE THREAD

**Issue by Vladyslava95** [ita-social-projects/SoftServeCar-Back-End#269]
**Reproducible:** always,
**Build found:** build 1.0.65

**Preconditions**
The "Car" app is opened
The "My Profile" page is opened

**Steps to reproduce**
1. Go to the 'Your Cars' page
2.  Observe the 'Save' button

**Actual result**
The "Save" button enabled if all fields are empty.

**Expected result**
The "Save" button is disabled if all fields are empty.

**User story and test case links**
E.g.: "User story #33

**Labels to be added**
"Bug" ("bug"), Priority ("pri: high
![photo_2021-02-25_10-17-08](https://user-images.githubusercontent.com/71496479/109124186-4e06ee00-7753-11eb-8c5e-2f168200f85a.jpg)
")

**Comment by AnnaBalah** [comment]
The issue is resolved only partially. This button is not clickable, but has a style of active button which is misleading.
Disabled buttons should have following colour: #B8B8B8.
Please check all of the buttons that have disabled state and update them accordingly. 

<img width="161" alt="US_2_CreateJourney_1" src="https://user-images.githubusercontent.com/81674765/115250142-f8870600-a131-11eb-925b-140c92ed8d63.png">
